In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("categories.csv")
df.head()

,id,parent_id,name,url_key,product_count,children_count
0,839,316,Sách văn học,sach-van-hoc,10000.0,21
1,4933,839,Du ký,du-ky,411.0,0
2,7358,839,Light novel,light-novel,1535.0,0
3,5244,839,Phê Bình - Lý Luận Văn Học,phe-binh-ly-luan-van-hoc,935.0,0
4,5245,839,Phóng sự - Ký sự - Bút ký,phong-su-ky-su,1451.0,2

In [10]:
leaf_category = df[df["children_count"] == 0]
print(len(leaf_category) , " / " , len(df))
print(leaf_category.head())

229  /  284
      id  parent_id                        name                   url_key  \
1   4933        839                       Du ký                     du-ky
2   7358        839                 Light novel               light-novel
3   5244        839  Phê Bình - Lý Luận Văn Học  phe-binh-ly-luan-van-hoc
5  67992       5245          Bút Ký - Tự Truyện          but-ky-tu-truyen
6  67993       5245            Phóng Sự - Ký Sự            phong-su-ky-su

   product_count  children_count
1          411.0               0
2         1535.0               0
3          935.0               0
5            NaN               0
6            NaN               0

In [11]:
full_url_link = leaf_category[["id", "name", "product_count"]].copy()

full_url_link["link"] = (
    "https://tiki.vn/"
    + leaf_category["url_key"].astype(str)
    + "/c"
    + leaf_category["id"].astype(str)
)

full_url_link.head()

,id,name,product_count,link
1,4933,Du ký,411.0,https://tiki.vn/du-ky/c4933
2,7358,Light novel,1535.0,https://tiki.vn/light-novel/c7358
3,5244,Phê Bình - Lý Luận Văn Học,935.0,https://tiki.vn/phe-binh-ly-luan-van-hoc/c5244
5,67992,Bút Ký - Tự Truyện,NaN,https://tiki.vn/but-ky-tu-truyen/c67992
6,67993,Phóng Sự - Ký Sự,NaN,https://tiki.vn/phong-su-ky-su/c67993

In [13]:
full_url_link = full_url_link.sort_values(["product_count", "id"], ascending=[True, True])

full_url_link.to_csv(
    "full_url_link.csv",
    index=False,
    encoding="utf-8-sig"
)